(function (global) {
  'use strict';

  var THERAPIES = [
    {
      title: 'Ketogenic therapy',
      body: 'Shifts metabolism away from glycolysis, starving cancer cells while restoring mitochondrial function.',
    },
    {
      title: 'Hyperbaric oxygen (HBOT)',
      body: 'Increases cellular oxygenation without inducing ROS damage. Do not perform without PEMF.',
    },
    {
      title: 'PEMF (10–50 Hz)',
      body: 'Stimulates mitochondrial ATP production while stabilizing function post-damage. 3–5× per week or as prescribed.',
    },
    {
      title: 'Mitochondrial support',
      body: 'NAD+, CoQ10, ALA, L-Carnitine, magnesium, PQQ, melatonin — rebuild energy pathways and counter chemo-induced damage.',
    },
  ];

  var PRESETS = [
    { psi: 150, label: '150 mV · nominal' },
    { psi: 145, label: '145 mV · floor' },
    { psi: 180, label: '180 mV · pathological' },
    { psi: 220, label: '220 mV · cancer band' },
  ];

  /**
   * Paper §5 parametric table: 142.8–220 mV (Walker 2026, 1, 1.3). Nominal healthy = 150 mV (§1).
   * Floor held at 143 mV: below ~138 mV ΔT → 0 and τ = ℏ/(k_B·ΔT) diverges, so the model reports
   * spurious "maximum coherence" right before collapse — a singularity artifact, not a healthier
   * state. The HEALTHY window is the ~27 K-gap setpoint, not the coherence peak.
   */
  var PSI_MIN = 143;
  var PSI_MAX = 220;

  var PAPER_METRICS = [
    { key: 'nu', sym: 'ν', unit: 'THz · §1', hero: true },
    { key: 'lambda', sym: 'λ', unit: 'μm · §2', hero: true },
    { key: 'deltaT', sym: 'ΔT', unit: 'K · §3', hero: true },
    { key: 'energy', sym: 'E', unit: 'J', sm: true },
    { key: 'omega', sym: 'ω', unit: 'rad/s', sm: true },
    { key: 'tWien', sym: 'T<sub>eff</sub>', unit: 'K · Wien', sm: true },
    { key: 'infoton', sym: 'm', unit: 'kg · §4', sm: true },
  ];

  var EXT_METRICS = [
    { key: 'tau', sym: 'τ', unit: 'coherence', sm: true },
    { key: 'atp', sym: 'ATP', unit: 'rel.' },
    { key: 'ros', sym: 'ROS', unit: 'rel.' },
    { key: 'vo2', sym: 'VO₂', unit: 'rel.' },
  ];

  var ADV_FIELDS = [
    {
      key: 'nu',
      label: 'ν (THz) · §1 heartbeat',
      inverse: 'psiFromNuThz',
      step: '0.01',
      min: '1',
      fmt: function (r) { return r.nuThz.toFixed(2); },
    },
    {
      key: 'lambda',
      label: 'λ (μm) · §2 LWIR',
      inverse: 'psiFromWavelengthUm',
      step: '0.01',
      min: '0.1',
      fmt: function (r) { return r.wavelengthUm.toFixed(2); },
    },
    {
      key: 'tWien',
      label: 'T (K) · §3 Wien',
      inverse: 'psiFromTWien',
      step: '0.1',
      min: '1',
      fmt: function (r) { return r.tWienK.toFixed(1); },
    },
    {
      key: 'infoton',
      label: 'Infoton mass (kg) · §4',
      inverse: 'psiFromInfotonMass',
      step: 'any',
      min: '0',
      fmt: function (r) { return r.infotonMass.toExponential(3); },
    },
  ];

  var STATE_RGB = {
    DYSREGULATED: [248, 113, 113],
    HEALTHY: [52, 211, 153],
    MILD_HYPERPOLARIZED: [253, 224, 71],
    PATHOLOGICAL: [251, 146, 60],
    CANCER: [239, 68, 68],
  };

  /**
   * Published conformance vectors — verbatim paper_chain values from
   * spec/mitochondria_vectors.json (generated by tools/gen_mitochondria_vectors.py,
   * the same suite tools/verify_mitochondria.py checks). Embedded (not fetched)
   * because spec/ is outside the deployed viz/ root. The reproducibility panel
   * recomputes each point live in-browser and compares to these to ≤ 1e-9 rel.
   */
  var REFERENCE_VECTORS = [
    { psi: 143, nu_thz: 34.577246183000476, wavelength_um: 8.670223661344949, delta_t_k: 11.221130640416504, infoton_mass_kg: 3.5587808252906363e-38 },
    { psi: 145, nu_thz: 35.06084403171376, wavelength_um: 8.55063436946433, delta_t_k: 15.895552047974661, infoton_mass_kg: 3.608553983686308e-38 },
    { psi: 150, nu_thz: 36.269838653497, wavelength_um: 8.265613223815517, delta_t_k: 27.58160556687045, infoton_mass_kg: 3.7329868796754926e-38 },
    { psi: 155, nu_thz: 37.47883327528024, wavelength_um: 7.998980539176307, delta_t_k: 39.26765908576613, infoton_mass_kg: 3.8574197756646757e-38 },
    { psi: 160, nu_thz: 38.687827897063464, wavelength_um: 7.749012397327049, delta_t_k: 50.95371260466169, infoton_mass_kg: 3.981852671653857e-38 },
    { psi: 165, nu_thz: 39.8968225188467, wavelength_um: 7.51419383983229, delta_t_k: 62.63976612355742, infoton_mass_kg: 4.106285567643041e-38 },
    { psi: 180, nu_thz: 43.5238063841964, wavelength_um: 6.888011019846265, delta_t_k: 97.6979266802445, infoton_mass_kg: 4.4795842556105905e-38 },
    { psi: 200, nu_thz: 48.35978487132934, wavelength_um: 6.199209917861638, delta_t_k: 144.44214075582727, infoton_mass_kg: 4.977315839567324e-38 },
    { psi: 220, nu_thz: 53.195763358462266, wavelength_um: 5.635645379874216, delta_t_k: 191.18635483140997, infoton_mass_kg: 5.475047423524056e-38 },
  ];
  var VECTOR_TOL_REL = 1e-9; // matches spec/mitochondria_vectors.json tolerance.rel

  /**
   * JC-1 aggregate:monomer (red:green) ratio → Δψ — ILLUSTRATIVE calibration only.
   * JC-1 forms red aggregates at high membrane potential, green monomers when
   * depolarized, so the ratio rises with Δψ. There is no validated universal
   * conversion; this is a transparent demo curve anchored at ratio 2.0 ≈ 150 mV,
   * meant to be replaced by a lab's own standard curve. Clearly labeled in the UI.
   */
  var JC1_ANCHOR_RATIO = 2.0;
  var JC1_ANCHOR_PSI = 150;
  var JC1_SLOPE = 24; // mV per doubling of ratio (illustrative)
  function psiFromJc1Ratio(ratio) {
    if (!(ratio > 0)) return null;
    return JC1_ANCHOR_PSI + JC1_SLOPE * (Math.log(ratio / JC1_ANCHOR_RATIO) / Math.LN2);
  }
  function jc1RatioFromPsi(psi) {
    return JC1_ANCHOR_RATIO * Math.pow(2, (psi - JC1_ANCHOR_PSI) / JC1_SLOPE);
  }

  // Guided "cancer paradox" reveal — the counterintuitive hyperpolarization story.
  var TOUR_STEPS = [
    { psi: 150, title: 'Start: the healthy anchor', body: 'At 150 mV the published chain gives ν ≈ 36.27 THz and a ~27 K coherence gap. This is the model setpoint.' },
    { psi: 145, title: 'Intuition: lower must be sicker?', body: 'Drop toward the floor — coherence is still high. Depolarization alone is not the whole story.' },
    { psi: 220, title: 'The paradox: hyperpolarization', body: 'Cancer-associated cells often run HIGH Δψ. Watch coherence collapse as ΔT runs away — high voltage, low coherence.' },
    { psi: 150, title: 'Why it matters', body: 'One reading cannot tell direction. The product thesis is the trajectory of this signal over time, not a single value.' },
  ];

  function stateRgb(id) {
    return STATE_RGB[id] || STATE_RGB.HEALTHY;
  }

  /** Coherence health on 0..1 (1 = fully coherent healthy band). Drives spiral damping.
   *  Delegates to the core so the widget, snapshot, and conformance vectors agree. */
  function coherenceUnit(r) {
    return global.P30MitoCore.coherenceUnit(r);
  }

  /**
   * Fission/Fusion ratio — TWO candidate models, surfaced side-by-side for review. Neither is
   * in the Walker paper or the infoton.ai calculator; both are exploratory mappings of Δψₘ.
   *
   * Model A — coherence-derived (platform heuristic): fission rises as quantum coherence (τ/τ_h)
   *   is lost. Symmetric: BOTH depolarization and hyperpolarization reduce coherence → fission.
   *
   * Model B — Δψ/literature-grounded: membrane depolarization drives fission via OPA1 cleavage,
   *   Drp1 recruitment and PINK1/Parkin mitophagy (Twig et al. 2008; Youle & van der Bliek 2012).
   *   F/F ≈ 1 at the ~150 mV set point, rises as Δψ falls, fusion-dominant when hyperpolarized.
   *
   * The two DISAGREE at the hyperpolarized (cancer) end — exactly the open question to flag.
   */
  function fissionFusionCoherence(r) {
    return global.P30MitoCore.fissionFusionCoherence(r);
  }

  function fissionFusionPsi(r) {
    return global.P30MitoCore.fissionFusionPsi(r);
  }

  function fmtTau(ps) {
    if (ps <= 0) return '—';
    if (ps < 1) return ps.toFixed(2) + ' ps';
    return ps.toFixed(1) + ' ps';
  }

  function clampPsi(psi) {
    return Math.min(PSI_MAX, Math.max(PSI_MIN, psi));
  }

  function gapFillPct(deltaTK) {
    if (deltaTK <= 0) return 0;
    var r220 = global.P30MitoCore.calculate(220);
    var maxGap = r220.deltaTK > 0 ? r220.deltaTK : 191;
    return Math.min((deltaTK / maxGap) * 100, 100);
  }

  // ── Diagnostic summary helpers (qualitative bands over real quantities) ──
  function diagCard(title, valKey, sub) {
    return (
      '<div class="wgt-mito-diag-card" data-wgt="' + valKey + 'Card">' +
        '<div class="wgt-mito-diag-title">' + title + '</div>' +
        '<div class="wgt-mito-diag-val" data-wgt="' + valKey + '">—</div>' +
        '<div class="wgt-mito-diag-lab" data-wgt="' + valKey + 'Lab">—</div>' +
        '<div class="wgt-mito-diag-sub">' + sub + '</div>' +
      '</div>'
    );
  }

  function phaseLabel(c) {
    if (c >= 0.85) return 'Healthy';
    if (c >= 0.65) return 'Mild drift';
    if (c >= 0.45) return 'Early disease';
    if (c >= 0.25) return 'Advanced';
    return 'Critical';
  }
  function entropyLabel(e) { return e < 0.33 ? 'Low' : e < 0.6 ? 'Moderate' : 'High'; }
  function curvLabel(v) { return v >= 0.7 ? 'Tight' : v >= 0.4 ? 'Loosening' : 'Unwound'; }
  function resoLabel(c) { return c >= 0.7 ? 'Stable' : c >= 0.5 ? 'Drifting' : 'Unstable'; }

  function sevCoh(c) { return c >= 0.7 ? 'good' : c >= 0.45 ? 'warn' : 'bad'; }
  function sevEntropy(e) { return e < 0.33 ? 'good' : e < 0.6 ? 'warn' : 'bad'; }
  function sevCurv(v) { return v >= 0.7 ? 'good' : v >= 0.4 ? 'warn' : 'bad'; }

  function metricBoxes(metrics, mod) {
    return metrics.map(function (m) {
      var cls = 'wgt-mito-box' + (m.hero ? ' wgt-mito-box-hero' : '') + (m.sm ? ' wgt-mito-box-sm' : '');
      if (mod) cls += ' ' + mod;
      return (
        '<div class="' + cls + '">' +
          '<div class="wgt-mito-box-sym">' + m.sym + '</div>' +
          '<div class="wgt-mito-box-val" data-wgt="' + m.key + '">—</div>' +
          '<div class="wgt-mito-box-unit">' + m.unit + '</div>' +
        '</div>'
      );
    }).join('');
  }

  function mountMitochondria(root) {
    var core = global.P30MitoCore;
    if (!core) {
      root.innerHTML = '<div class="demo-error">Mitochondria core failed to load.</div>';
      return { destroy: function () { root.innerHTML = ''; } };
    }

    var listeners = [];
    var syncing = false;

    function on(el, ev, fn) {
      if (!el) return;
      el.addEventListener(ev, fn);
      listeners.push([el, ev, fn]);
    }

    var therapyHtml = THERAPIES.map(function (t) {
      return (
        '<div class="wgt-mito-care">' +
          '<div class="wgt-mito-care-title">' + t.title + '</div>' +
          '<div class="wgt-mito-care-body">' + t.body + '</div>' +
        '</div>'
      );
    }).join('');

    var presetHtml = PRESETS.map(function (p) {
      return '<button type="button" class="wgt-mito-preset" data-wgt="preset-' + p.psi + '">' + p.label + '</button>';
    }).join('');

    var advFieldsHtml = ADV_FIELDS.map(function (f) {
      var minAttr = f.min !== undefined ? ' min="' + f.min + '"' : '';
      return (
        '<label class="wgt-mito-adv-field">' +
          '<span class="wgt-mito-adv-lab">' + f.label + '</span>' +
          '<input type="number" data-wgt="adv-' + f.key + '" step="' + f.step + '"' + minAttr + '>' +
        '</label>'
      );
    }).join('');

    root.innerHTML =
      '<div class="wgt wgt-mito">' +
        '<div class="wgt-stage wgt-stage-mito">' +
          '<div class="wgt-work">' +
            '<header class="wgt-mito-head">' +
              '<div>' +
                '<div class="wgt-work-title">Quantum Heartbeat</div>' +
                '<p class="wgt-mito-lead">' +
                  'One membrane potential drives the published chain — drag Δψ<sub>m</sub>, or back-solve from any §1–§4 column.' +
                '</p>' +
              '</div>' +
              '<div class="wgt-mito-toolbar">' +
                '<button type="button" class="wgt-mito-tool" data-wgt="heartBtn" aria-pressed="false" title="Play the audible heartbeat">' +
                  '<span class="wgt-mito-tool-ico" aria-hidden="true">♪</span><span data-wgt="heartLab">Heartbeat</span>' +
                '</button>' +
                '<button type="button" class="wgt-mito-tool" data-wgt="tourBtn" title="Guided 30-second reveal">▶ Tour</button>' +
                '<button type="button" class="wgt-mito-tool" data-wgt="shareBtn" title="Copy a link to this Δψ">Share</button>' +
                '<button type="button" class="wgt-mito-tool" data-wgt="snapBtn" title="Download a snapshot card (PNG)">Snapshot</button>' +
              '</div>' +
            '</header>' +

            '<div class="wgt-mito-tour" data-wgt="tour" hidden>' +
              '<div class="wgt-mito-tour-body">' +
                '<div class="wgt-mito-tour-step" data-wgt="tourStep">Step</div>' +
                '<div class="wgt-mito-tour-title" data-wgt="tourTitle">Title</div>' +
                '<div class="wgt-mito-tour-text" data-wgt="tourText">Text</div>' +
              '</div>' +
              '<div class="wgt-mito-tour-actions">' +
                '<button type="button" class="wgt-mito-tour-btn" data-wgt="tourSkip">Skip</button>' +
                '<button type="button" class="wgt-mito-tour-btn wgt-mito-tour-next" data-wgt="tourNext">Next →</button>' +
              '</div>' +
            '</div>' +

            '<section class="wgt-mito-state-card" aria-live="polite">' +
              '<div class="wgt-mito-state-lab">Mitochondrial state</div>' +
              '<div class="wgt-work-tag wgt-mito-state wgt-mito-state-big state-healthy" data-wgt="stateBadge">HEALTHY</div>' +
              '<p class="wgt-mito-desc" data-wgt="stateDesc"></p>' +
            '</section>' +

            '<section class="wgt-mito-card wgt-mito-driver">' +
              '<label class="wgt-mito-lab" for="wgt-mito-slider">' +
                'Membrane potential Δψ<sub>m</sub> ' +
                '<span class="wgt-mito-lab-tag">primary · §5 driver</span>' +
              '</label>' +
              '<div class="wgt-mito-band" aria-hidden="true"></div>' +
              '<div class="wgt-mito-psi-row">' +
                '<input type="range" id="wgt-mito-slider" data-wgt="slider" min="' + PSI_MIN + '" max="' + PSI_MAX + '" step="1" value="150">' +
                '<span class="wgt-mito-psi-val"><span data-wgt="psiVal">150</span><span class="wgt-mito-psi-unit">mV</span></span>' +
              '</div>' +
              '<div class="wgt-mito-scale">' +
                '<span>142.8 mV</span>' +
                '<span>150 mV nominal (§1)</span>' +
                '<span>220 mV</span>' +
              '</div>' +
              '<div class="wgt-mito-presets">' + presetHtml + '</div>' +
              '<div class="wgt-mito-assay">' +
                '<label class="wgt-mito-assay-lab" for="wgt-mito-jc1">' +
                  'JC-1 assay · aggregate : monomer (red/green) ratio' +
                '</label>' +
                '<div class="wgt-mito-assay-row">' +
                  '<input type="number" id="wgt-mito-jc1" data-wgt="jc1" step="0.05" min="0.1" inputmode="decimal">' +
                  '<span class="wgt-mito-assay-arrow">→ <span data-wgt="jc1Psi">150</span> mV</span>' +
                '</div>' +
                '<p class="wgt-mito-assay-note">Illustrative calibration (anchor: ratio 2.0 ≈ 150 mV) — replace with your lab\u2019s validated curve. Research-use, not a diagnostic conversion.</p>' +
              '</div>' +
              '<div class="wgt-mito-coh">' +
                '<div class="wgt-mito-coh-head">' +
                  '<span>Coherence gap ΔT (T<sub>eff</sub> − T<sub>bath</sub>) · §3</span>' +
                  '<span data-wgt="gapReadout">28 K</span>' +
                '</div>' +
                '<div class="wgt-mito-coh-track"><div class="wgt-mito-coh-fill" data-wgt="cohFill"></div></div>' +
                '<div class="wgt-mito-cont">' +
                  '<div class="wgt-mito-cont-bar">' +
                    '<span class="wgt-mito-cont-marker" data-wgt="contMarker"></span>' +
                  '</div>' +
                  '<div class="wgt-mito-cont-labels">' +
                    '<span>Collapsed</span><span>Decoherent</span><span>Drifting</span><span>Coherent</span>' +
                  '</div>' +
                '</div>' +
              '</div>' +
            '</section>' +

            '<section class="wgt-mito-card wgt-mito-deriv-live">' +
              '<div class="wgt-mito-section-head">' +
                '<span class="wgt-mito-out-label">Live derivation · substituted in real time</span>' +
              '</div>' +
              '<ol class="wgt-mito-chain">' +
                '<li class="wgt-mito-chain-step"><span class="wgt-mito-chain-sec">§1</span><span class="wgt-mito-chain-math" data-wgt="dvE">E = e·Δψ</span></li>' +
                '<li class="wgt-mito-chain-step"><span class="wgt-mito-chain-sec">§1</span><span class="wgt-mito-chain-math" data-wgt="dvNu">ω = E/ℏ → ν</span></li>' +
                '<li class="wgt-mito-chain-step"><span class="wgt-mito-chain-sec">§2</span><span class="wgt-mito-chain-math" data-wgt="dvLam">λ = c/ν</span></li>' +
                '<li class="wgt-mito-chain-step"><span class="wgt-mito-chain-sec">§3</span><span class="wgt-mito-chain-math" data-wgt="dvDT">ΔT = W/λ − T_bath</span></li>' +
                '<li class="wgt-mito-chain-step"><span class="wgt-mito-chain-sec">§4</span><span class="wgt-mito-chain-math" data-wgt="dvM">m = k_B·T·ln2/c²</span></li>' +
                '<li class="wgt-mito-chain-step"><span class="wgt-mito-chain-sec">ext</span><span class="wgt-mito-chain-math" data-wgt="dvTau">τ = ℏ/(k_B·ΔT)</span></li>' +
              '</ol>' +
            '</section>' +

            '<section class="wgt-mito-card wgt-mito-viz-card">' +
              '<div class="wgt-mito-section-head">' +
                '<span class="wgt-mito-out-label">Cell state · real-time bioenergetic coherence</span>' +
              '</div>' +
              '<div class="wgt-mito-viz">' +
                '<figure class="wgt-mito-viz-panel">' +
                  '<figcaption class="wgt-mito-viz-title">Coherence phase spiral</figcaption>' +
                  '<canvas class="wgt-mito-canvas" data-wgt="spiralCanvas"></canvas>' +
                  '<div class="wgt-mito-viz-cap" data-wgt="spiralCap">—</div>' +
                '</figure>' +
                '<figure class="wgt-mito-viz-panel">' +
                  '<figcaption class="wgt-mito-viz-title">Biomarker profile</figcaption>' +
                  '<canvas class="wgt-mito-canvas" data-wgt="radarCanvas"></canvas>' +
                  '<div class="wgt-mito-viz-legend">' +
                    '<span class="wgt-mito-leg wgt-mito-leg-normal">Normal Range</span>' +
                    '<span class="wgt-mito-leg wgt-mito-leg-current" data-wgt="radarLeg">Current Values</span>' +
                  '</div>' +
                '</figure>' +
              '</div>' +
              '<details class="wgt-mito-ff" data-wgt="ffCompare">' +
                '<summary class="wgt-mito-ff-tag">Fission/Fusion · P30 exploratory — not in the infoton.ai reference</summary>' +
                '<div class="wgt-mito-ff-body">' +
                  '<span class="wgt-mito-ff-row"><span class="wgt-mito-ff-k">coherence model</span><span class="wgt-mito-ff-v" data-wgt="ffCoh">—</span></span>' +
                  '<span class="wgt-mito-ff-row"><span class="wgt-mito-ff-k">Δψ · literature</span><span class="wgt-mito-ff-v" data-wgt="ffPsi">—</span></span>' +
                  '<span class="wgt-mito-ff-note" data-wgt="ffNote"></span>' +
                '</div>' +
              '</details>' +
            '</section>' +

            '<section class="wgt-mito-card wgt-mito-viz-card">' +
              '<div class="wgt-mito-section-head">' +
                '<span class="wgt-mito-out-label">Dynamics &amp; systems view</span>' +
              '</div>' +
              '<div class="wgt-mito-viz">' +
                '<figure class="wgt-mito-viz-panel">' +
                  '<figcaption class="wgt-mito-viz-title">Phase trajectory</figcaption>' +
                  '<canvas class="wgt-mito-canvas" data-wgt="trajCanvas"></canvas>' +
                  '<div class="wgt-mito-viz-legend">' +
                    '<span class="wgt-mito-leg wgt-mito-leg-coh">Phase coherence</span>' +
                    '<span class="wgt-mito-leg wgt-mito-leg-risk">Risk = 1 − coherence</span>' +
                  '</div>' +
                  '<div class="wgt-mito-viz-cap" data-wgt="trajCap">replay of your Δψ history · each point a real calc</div>' +
                '</figure>' +
                '<figure class="wgt-mito-viz-panel">' +
                  '<figcaption class="wgt-mito-viz-title">Network coherence</figcaption>' +
                  '<canvas class="wgt-mito-canvas" data-wgt="netCanvas"></canvas>' +
                  '<div class="wgt-mito-viz-cap" data-wgt="netCap">uniform Δψ across organs · no per-organ assumptions</div>' +
                '</figure>' +
              '</div>' +
            '</section>' +

            '<section class="wgt-mito-card wgt-mito-diag">' +
              '<div class="wgt-mito-section-head">' +
                '<span class="wgt-mito-out-label">Diagnostic summary</span>' +
              '</div>' +
              '<div class="wgt-mito-diag-grid">' +
                diagCard('Phase Coherence', 'phaseCoh', 'τ / τ_healthy · real') +
                diagCard('Entropy Level', 'entropy', 'derived · ∝ ΔT') +
                diagCard('Spiral Curvature', 'curv', 'derived · ∝ Q') +
                diagCard('Resonance ν (THz)', 'reso', 'ν = ω/2π · §1') +
              '</div>' +
              '<div class="wgt-mito-diag-actions">' +
                '<button type="button" class="wgt-mito-sim" data-wgt="simUpdate">↻ Replay analysis</button>' +
                '<button type="button" class="wgt-mito-sim wgt-mito-sim-bad" data-wgt="simDisease">Simulate disease →</button>' +
                '<button type="button" class="wgt-mito-sim wgt-mito-sim-good" data-wgt="simRecovery">Simulate recovery →</button>' +
              '</div>' +
            '</section>' +

            '<div class="wgt-mito-flow" aria-hidden="true">' +
              '<span>Δψ</span><span class="wgt-mito-flow-arr">→</span>' +
              '<span>E</span><span class="wgt-mito-flow-arr">→</span>' +
              '<span>ω</span><span class="wgt-mito-flow-arr">→</span>' +
              '<span>ν</span><span class="wgt-mito-flow-arr">→</span>' +
              '<span>λ</span><span class="wgt-mito-flow-arr">→</span>' +
              '<span>T</span><span class="wgt-mito-flow-arr">→</span>' +
              '<span>ΔT</span><span class="wgt-mito-flow-arr">→</span>' +
              '<span>m</span>' +
            '</div>' +

            '<section class="wgt-mito-card">' +
              '<div class="wgt-mito-section-head">' +
                '<span class="wgt-mito-out-label">Paper chain · §1–§5</span>' +
                '<button type="button" class="wgt-mito-copy" data-wgt="copyBtn">Copy parameters</button>' +
              '</div>' +
              '<div class="wgt-mito-param-grid">' + metricBoxes(PAPER_METRICS) + '</div>' +
            '</section>' +

            '<section class="wgt-mito-card wgt-mito-repro">' +
              '<div class="wgt-mito-section-head">' +
                '<span class="wgt-mito-out-label">Reproducibility · live conformance check</span>' +
                '<button type="button" class="wgt-mito-copy" data-wgt="reproBtn">Re-run check</button>' +
              '</div>' +
              '<p class="wgt-mito-repro-lead">' +
                'Every row is recomputed in your browser right now and compared to the published ' +
                '<a href="https://zenodo.org/records/18373065" target="_blank" rel="noopener">Zenodo</a> ' +
                'conformance vectors (spec/mitochondria_vectors.json) — the same suite verify_mitochondria.py runs in CI.' +
              '</p>' +
              '<div class="wgt-mito-repro-summary" data-wgt="reproSummary" aria-live="polite">—</div>' +
              '<div class="wgt-mito-repro-rows" data-wgt="reproRows"></div>' +
            '</section>' +

            '<details class="wgt-mito-adv">' +
              '<summary class="wgt-mito-adv-toggle">Advanced · back-solve Δψ<sub>m</sub></summary>' +
              '<p class="wgt-mito-adv-lead">' +
                'Edit a downstream quantity from §1–§4 to invert the chain — same columns as Walker (2026) Table 5.' +
              '</p>' +
              '<div class="wgt-mito-adv-grid">' + advFieldsHtml + '</div>' +
            '</details>' +

            '<section class="wgt-mito-card wgt-mito-card-ext">' +
              '<div class="wgt-mito-out-label wgt-mito-out-ext">Virtual Mitochondria extension · not in §5 table</div>' +
              '<p class="wgt-mito-bridge">' +
                'τ, ATP, ROS, and VO₂ are platform heuristics (infoton.ai). The paper chain above is deterministic — ' +
                'composable with whole-cell and assay pipelines.' +
              '</p>' +
              '<div class="wgt-mito-param-grid wgt-mito-param-ext">' + metricBoxes(EXT_METRICS, 'wgt-mito-box-ext') + '</div>' +
            '</section>' +

            '<div class="wgt-caption">' +
              'Walker (2026) Januarian Physics 1, 1.3 · T<sub>bath</sub> = 323 K · 150 mV → 36.25 THz, 8.27 μm, 350.4 K, 27 K gap.' +
            '</div>' +
          '</div>' +

          '<aside class="wgt-panel wgt-mito-panel">' +
            '<div class="wgt-p-block">' +
              '<div class="wgt-p-title">Paper chain (§1–§4)</div>' +
              '<div class="wgt-deriv wgt-mito-deriv">' +
                '<div class="wgt-dstep"><span class="wgt-dnum">§1</span><div class="wgt-dbody"><span class="wgt-dmath">E = e·Δψ<sub>m</sub>, ω = E/ℏ, ν = ω/2π → 36.25 THz @ 150 mV</span></div></div>' +
                '<div class="wgt-dstep"><span class="wgt-dnum">§2</span><div class="wgt-dbody"><span class="wgt-dmath">λ = c/ν → 8.27 μm (LWIR window)</span></div></div>' +
                '<div class="wgt-dstep"><span class="wgt-dnum">§3</span><div class="wgt-dbody"><span class="wgt-dmath">T = W/λ → 350.4 K; ΔT = T − T<sub>bath</sub> → 27 K gap</span></div></div>' +
                '<div class="wgt-dstep"><span class="wgt-dnum">§4</span><div class="wgt-dbody"><span class="wgt-dmath">m = k<sub>B</sub>T ln(2)/c² → 3.724×10⁻³⁸ kg</span></div></div>' +
                '<div class="wgt-dstep"><span class="wgt-dnum">§5</span><div class="wgt-dbody"><span class="wgt-dmath">Δψₘ predicts all columns (142.8–220 mV table)</span></div></div>' +
              '</div>' +
            '</div>' +
            '<details class="wgt-mito-panel-fold">' +
              '<summary class="wgt-p-title wgt-mito-panel-fold-title">Care pathways (adjunct)</summary>' +
              '<div class="wgt-mito-care-wrap">' + therapyHtml + '</div>' +
            '</details>' +
            '<div class="wgt-p-block">' +
              '<div class="wgt-p-title">Learn more</div>' +
              '<p class="wgt-mito-ref wgt-mito-ref-lead">' +
                'The paper is the source of truth. The live site is the reference calculator. ' +
                'The video is January walking the chain in plain language.' +
              '</p>' +
              '<nav class="wgt-mito-links" aria-label="Research and media">' +
                '<a class="wgt-mito-link" href="https://infoton.ai/mitochondria" target="_blank" rel="noopener">Live calculator · infoton.ai →</a>' +
                '<a class="wgt-mito-link" href="https://zenodo.org/records/18373065" target="_blank" rel="noopener">Paper · Zenodo 18373065 →</a>' +
                '<a class="wgt-mito-link" href="https://www.youtube.com/watch?v=Kkt7Bfz8NFU" target="_blank" rel="noopener">Video walkthrough →</a>' +
              '</nav>' +
            '</div>' +
          '</aside>' +
        '</div>' +
      '</div>';

    function q(name) {
      return root.querySelector('[data-wgt="' + name + '"]');
    }

    function setText(name, text) {
      var el = q(name);
      if (el) el.textContent = text;
    }

    function setDiag(key, val, lab, sev) {
      setText(key, val);
      setText(key + 'Lab', lab);
      var card = q(key + 'Card');
      if (card) card.className = 'wgt-mito-diag-card wgt-mito-diag-' + sev;
    }

    var ENTROPY_MAX = (function () {
      var c = core.calculate(220);
      return c.deltaTK > 0 ? c.deltaTK : 191;
    })();
    var CYCLES_HEALTHY = (function () {
      var h = core.calculate(150);
      return h.tauCohS > 0 ? (h.omegaRadS * h.tauCohS) / (2 * Math.PI) : 10;
    })();

    var lastR = null;
    var history = []; // replay of real Δψ → coherence/risk samples (each a real calc)
    var HISTORY_MAX = 60;

    // RdYlGn-style coherence colormap: 0 = red, 0.5 = yellow, 1 = green.
    function coherenceColor(c, alpha) {
      var hue = 120 * Math.max(0, Math.min(1, c));
      return 'hsla(' + hue.toFixed(0) + ', 70%, 48%, ' + (alpha == null ? 1 : alpha) + ')';
    }

    function fitCanvas(canvas, aspect) {
      var rect = canvas.getBoundingClientRect();
      var cssW = rect.width || canvas.parentNode.clientWidth || 280;
      var cssH = cssW * (aspect || 0.82);
      var dpr = window.devicePixelRatio || 1;
      canvas.style.height = cssH + 'px';
      canvas.width = Math.round(cssW * dpr);
      canvas.height = Math.round(cssH * dpr);
      var ctx = canvas.getContext('2d');
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      return { ctx: ctx, w: cssW, h: cssH };
    }

    function drawSpiral(r, progress, pulse) {
      var canvas = q('spiralCanvas');
      if (!canvas) return;
      if (progress === undefined) progress = 1;
      if (pulse === undefined) pulse = 0;
      var fit = fitCanvas(canvas, 0.82);
      var ctx = fit.ctx, w = fit.w, h = fit.h;
      ctx.clearRect(0, 0, w, h);

      var cx = w * 0.52;
      var cy = h * 0.46;
      var scale = Math.min(w, h) * 0.3;
      var zH = h * 0.36;
      var ax = 0.52;
      var cosA = Math.cos(ax);
      var sinA = Math.sin(ax);

      function project(x, y, z) {
        return {
          x: cx + (x - y) * cosA * scale,
          y: cy + (x + y) * sinA * scale - (z - 0.5) * zH,
        };
      }

      // faint floor grid for depth
      ctx.strokeStyle = 'rgba(167, 243, 208, 0.12)';
      ctx.lineWidth = 1;
      var g;
      for (g = -1; g <= 1; g += 0.5) {
        var a1 = project(g, -1, 0);
        var a2 = project(g, 1, 0);
        var b1 = project(-1, g, 0);
        var b2 = project(1, g, 0);
        ctx.beginPath(); ctx.moveTo(a1.x, a1.y); ctx.lineTo(a2.x, a2.y); ctx.stroke();
        ctx.beginPath(); ctx.moveTo(b1.x, b1.y); ctx.lineTo(b2.x, b2.y); ctx.stroke();
      }

      // coherence z-axis (back-left corner) with ticks + label
      var axisBase = project(-1, -1, 0);
      var axisTop = project(-1, -1, 1);
      ctx.strokeStyle = 'rgba(167, 243, 208, 0.3)';
      ctx.lineWidth = 1;
      ctx.beginPath(); ctx.moveTo(axisBase.x, axisBase.y); ctx.lineTo(axisTop.x, axisTop.y); ctx.stroke();
      ctx.fillStyle = 'rgba(220, 252, 231, 0.45)';
      ctx.font = "500 8px 'Cinzel', serif";
      ctx.textAlign = 'right';
      ctx.textBaseline = 'middle';
      var tick;
      for (tick = 0; tick <= 1.001; tick += 0.5) {
        var tp = project(-1, -1, tick);
        ctx.beginPath(); ctx.moveTo(tp.x, tp.y); ctx.lineTo(tp.x - 4, tp.y); ctx.stroke();
        ctx.fillText(tick.toFixed(1), tp.x - 6, tp.y);
      }
      ctx.save();
      ctx.translate(axisTop.x - 18, (axisTop.y + axisBase.y) / 2);
      ctx.rotate(-Math.PI / 2);
      ctx.textAlign = 'center';
      ctx.fillStyle = 'rgba(167, 243, 208, 0.6)';
      ctx.font = "600 9px 'Cinzel', serif";
      ctx.fillText('COHERENCE', 0, 0);
      ctx.restore();

      // ── Decoherence trajectory (damped quantum oscillator) ───────────
      //   ζ(t) = e^(−t/τ) · e^(iωt)   →   x = e^(−t/τ)cos(ωt), y = e^(−t/τ)sin(ωt)
      // z-axis = coherence amplitude e^(−t/τ). ω = r.omegaRadS, τ = r.tauCohS (both exact).
      // Q = ω·τ → cycles = ω·τ/2π = the true number of coherent oscillations. As ΔT → 0
      // (Δψ ≈ 138 mV) τ and Q diverge, so the VISIBLE turn count is capped at TURN_CAP to
      // stay legible; the window shrinks (uEnd) to keep the envelope honest. The exact Q is
      // always reported in the caption — only how much of the trajectory we draw is bounded.
      var rgb = stateRgb(r.state.id);
      var tauS = r.tauCohS;
      var omega = r.omegaRadS;
      var i, s, u, amp, phase, x, y, z, p, prev = null, hue, light;
      var collapsed = !(tauS > 0);

      var cycles = collapsed ? 0 : (omega * tauS) / (2 * Math.PI);
      var qRad = collapsed ? 0 : omega * tauS;
      var TURN_CAP = 5;
      var turnsShown = collapsed ? 0 : Math.min(cycles, TURN_CAP);
      var uEnd = cycles > 0 ? turnsShown / cycles : 0; // time window in units of τ (≤ 1)
      var N = collapsed ? 0 : Math.max(120, Math.min(900, Math.ceil(turnsShown * 64)));
      var drawN = Math.floor(N * progress);

      ctx.lineCap = 'round';
      for (i = 1; i <= drawN; i++) {
        s = i / N;
        u = uEnd * s;             // elapsed time in units of τ (bounded)
        amp = Math.exp(-u);       // coherence amplitude e^(−t/τ)
        phase = 2 * Math.PI * turnsShown * s;
        x = amp * Math.cos(phase);
        y = amp * Math.sin(phase);
        z = amp;
        p = project(x, y, z);
        if (prev) {
          hue = 140 * amp;            // green (coherent) → red (decohered)
          light = 44 + amp * 18;
          ctx.strokeStyle = 'hsla(' + hue + ', 78%, ' + light + '%, 1)';
          ctx.lineWidth = 2.4;
          ctx.beginPath();
          ctx.moveTo(prev.x, prev.y);
          ctx.lineTo(p.x, p.y);
          ctx.stroke();
        }
        prev = p;
      }

      // leading head dot while tracing
      if (!collapsed && progress < 1 && prev) {
        ctx.fillStyle = 'rgba(236, 253, 245, 0.9)';
        ctx.beginPath();
        ctx.arc(prev.x, prev.y, 3, 0, 2 * Math.PI);
        ctx.fill();
      }

      // decohered core marker — fades in at trace end, then pulses (faster when degraded)
      var markerAlpha = collapsed ? 1 : Math.max(0, Math.min(1, (progress - 0.8) / 0.2));
      if (markerAlpha > 0) {
        var endAmp = collapsed ? 0 : Math.exp(-uEnd);
        var end = collapsed
          ? project(0, 0, 0)
          : project(endAmp * Math.cos(2 * Math.PI * turnsShown), endAmp * Math.sin(2 * Math.PI * turnsShown), endAmp);
        var coh = coherenceUnit(r);
        var pulseRate = 1.4 + (1 - coh) * 2.6;
        var pulseAmt = 0.5 + 0.5 * Math.sin(pulse * pulseRate * Math.PI);
        var glowR = (11 + (1 - coh) * 4) + pulseAmt * (3 + (1 - coh) * 5);
        var grd = ctx.createRadialGradient(end.x, end.y, 1, end.x, end.y, glowR);
        grd.addColorStop(0, 'rgba(' + rgb[0] + ',' + rgb[1] + ',' + rgb[2] + ',' + (0.9 * markerAlpha) + ')');
        grd.addColorStop(1, 'rgba(' + rgb[0] + ',' + rgb[1] + ',' + rgb[2] + ',0)');
        ctx.fillStyle = grd;
        ctx.beginPath();
        ctx.arc(end.x, end.y, glowR, 0, 2 * Math.PI);
        ctx.fill();
        ctx.globalAlpha = markerAlpha;
        ctx.fillStyle = 'rgb(' + rgb[0] + ',' + rgb[1] + ',' + rgb[2] + ')';
        ctx.beginPath();
        ctx.arc(end.x, end.y, 5, 0, 2 * Math.PI);
        ctx.fill();
        ctx.globalAlpha = 1;
      }

      var cap = q('spiralCap');
      if (cap) {
        if (collapsed) {
          cap.textContent = 'coherence collapsed · ΔT ≤ 0 → τ → 0 (no sustained oscillation)';
        } else {
          cap.textContent = 'Q = ω·τ ≈ ' + qRad.toFixed(0) + ' rad → ' + cycles.toFixed(1) +
            ' coherent cycles · τ ' + fmtTau(r.tauCohPs);
        }
      }
    }

    function radarAxes(r) {
      // All four axes are reference biomarkers from the infoton.ai embed (Δψ → ATP/ROS/VO₂).
      return [
        { label: ['ROS', 'Level'], val: Math.max(0, Math.min(1, r.ros / 3)) },
        { label: ['Membrane', 'Potential'], val: Math.max(0, Math.min(1, (r.psiMmV - 130) / 100)) },
        { label: ['VO\u2082', 'Uptake'], val: Math.max(0, Math.min(1, r.vo2)) },
        { label: ['ATP', 'Production'], val: Math.max(0, Math.min(1, r.atp / 4)) },
      ];
    }

    function drawRadar(r) {
      var canvas = q('radarCanvas');
      if (!canvas) return;
      var fit = fitCanvas(canvas, 0.82);
      var ctx = fit.ctx, w = fit.w, h = fit.h;
      ctx.clearRect(0, 0, w, h);

      var cx = w / 2;
      var cy = h / 2 + 4;
      var radius = Math.min(w, h) * 0.34;
      var axes = radarAxes(r);
      var normal = radarAxes(core.calculate(150));
      var n = axes.length;
      var k, ang, gx, gy, ring;

      function pt(idx, frac) {
        var a = -Math.PI / 2 + (idx / n) * 2 * Math.PI;
        return { x: cx + Math.cos(a) * radius * frac, y: cy + Math.sin(a) * radius * frac };
      }

      // rings + radial Low/Normal/High labels (along the +x axis, like the reference)
      var ringFracs = [0.33, 0.67, 1.0];
      var ringNames = ['Low', 'Normal', 'High'];
      ctx.strokeStyle = 'rgba(167, 243, 208, 0.16)';
      ctx.lineWidth = 1;
      ringFracs.forEach(function (rf) {
        ctx.beginPath();
        for (k = 0; k <= n; k++) {
          var rp = pt(k % n, rf);
          if (k === 0) ctx.moveTo(rp.x, rp.y); else ctx.lineTo(rp.x, rp.y);
        }
        ctx.stroke();
      });
      ctx.fillStyle = 'rgba(220, 252, 231, 0.4)';
      ctx.font = "500 8px 'Cinzel', serif";
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ringFracs.forEach(function (rf, ri) {
        ctx.fillText(ringNames[ri], cx, cy + radius * rf + 0.5);
      });

      // spokes + (multi-line) axis labels
      ctx.fillStyle = 'rgba(220, 252, 231, 0.66)';
      ctx.font = "600 9px 'Cinzel', serif";
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      for (k = 0; k < n; k++) {
        ang = -Math.PI / 2 + (k / n) * 2 * Math.PI;
        gx = cx + Math.cos(ang) * radius;
        gy = cy + Math.sin(ang) * radius;
        ctx.strokeStyle = 'rgba(167, 243, 208, 0.16)';
        ctx.beginPath(); ctx.moveTo(cx, cy); ctx.lineTo(gx, gy); ctx.stroke();
        var lines = axes[k].label;
        var lx = cx + Math.cos(ang) * (radius + 16);
        var ly = cy + Math.sin(ang) * (radius + 15);
        ctx.fillStyle = 'rgba(220, 252, 231, 0.66)';
        var lh = 9;
        var y0 = ly - (lines.length - 1) * lh / 2;
        lines.forEach(function (ln, li) {
          ctx.fillText(ln, lx, y0 + li * lh);
        });
      }

      function polygon(data, stroke, fill, dashed) {
        ctx.beginPath();
        for (k = 0; k <= n; k++) {
          var d = data[k % n];
          var pp = pt(k % n, Math.max(0.05, d.val));
          if (k === 0) ctx.moveTo(pp.x, pp.y); else ctx.lineTo(pp.x, pp.y);
        }
        if (dashed) ctx.setLineDash([5, 4]); else ctx.setLineDash([]);
        if (fill) { ctx.fillStyle = fill; ctx.fill(); }
        ctx.strokeStyle = stroke;
        ctx.lineWidth = 2;
        ctx.stroke();
        ctx.setLineDash([]);
      }

      polygon(normal, 'rgba(52, 211, 153, 0.7)', null, true);
      var rgb = stateRgb(r.state.id);
      polygon(
        axes,
        'rgb(' + rgb[0] + ',' + rgb[1] + ',' + rgb[2] + ')',
        'rgba(' + rgb[0] + ',' + rgb[1] + ',' + rgb[2] + ',0.18)',
        false
      );
    }

    // ── Phase trajectory: replay of the user's real Δψ history ──────────
    // Every sample is an exact calculator output (coherence = τ/τ_h, capped).
    // Risk = 1 − coherence. No invented dynamics; the x-axis is what the user did.
    function drawTraj() {
      var canvas = q('trajCanvas');
      if (!canvas) return;
      var fit = fitCanvas(canvas, 0.82);
      var ctx = fit.ctx, w = fit.w, h = fit.h;
      ctx.clearRect(0, 0, w, h);

      var padL = 26, padR = 8, padT = 10, padB = 20;
      var plotW = w - padL - padR, plotH = h - padT - padB;
      function X(i, n) { return padL + (n <= 1 ? plotW : (i / (n - 1)) * plotW); }
      function Y(v) { return padT + (1 - Math.max(0, Math.min(1, v))) * plotH; }

      // y grid + ticks (0, 0.5, 1)
      ctx.strokeStyle = 'rgba(167, 243, 208, 0.12)';
      ctx.fillStyle = 'rgba(220, 252, 231, 0.5)';
      ctx.font = "500 9px 'Cinzel', serif";
      ctx.textAlign = 'right';
      ctx.textBaseline = 'middle';
      var yt;
      for (yt = 0; yt <= 1.001; yt += 0.5) {
        ctx.beginPath(); ctx.moveTo(padL, Y(yt)); ctx.lineTo(w - padR, Y(yt)); ctx.stroke();
        ctx.fillText(yt.toFixed(1), padL - 4, Y(yt));
      }

      // coherence threshold bands (0.9 green / 0.7 yellow / 0.5 red)
      var bands = [[0.9, 'rgba(52, 211, 153, 0.55)'], [0.7, 'rgba(250, 204, 21, 0.5)'], [0.5, 'rgba(248, 113, 113, 0.5)']];
      ctx.setLineDash([4, 3]);
      ctx.lineWidth = 1;
      bands.forEach(function (b) {
        ctx.strokeStyle = b[1];
        ctx.beginPath(); ctx.moveTo(padL, Y(b[0])); ctx.lineTo(w - padR, Y(b[0])); ctx.stroke();
      });
      ctx.setLineDash([]);

      var n = history.length;
      if (n === 0) return;

      function line(key, color, dots) {
        ctx.strokeStyle = color;
        ctx.lineWidth = 2;
        ctx.beginPath();
        history.forEach(function (pt, i) {
          var x = X(i, n), y = Y(pt[key]);
          if (i === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y);
        });
        ctx.stroke();
        if (dots) {
          ctx.fillStyle = color;
          history.forEach(function (pt, i) {
            ctx.beginPath(); ctx.arc(X(i, n), Y(pt[key]), 1.8, 0, 2 * Math.PI); ctx.fill();
          });
        }
      }

      line('risk', 'rgba(248, 113, 113, 0.95)', false);
      line('coh', 'rgba(96, 165, 250, 0.98)', true);

      // x label
      ctx.fillStyle = 'rgba(220, 252, 231, 0.45)';
      ctx.font = "500 9px 'Cinzel', serif";
      ctx.textAlign = 'center';
      ctx.textBaseline = 'bottom';
      ctx.fillText('Δψ history →', padL + plotW / 2, h - 2);
    }

    // ── Network coherence: one shared Δψ across organs (uniform response) ─
    // No per-organ baselines; every node is the SAME real calculation, so the
    // whole network shifts color together. Topology is an illustrative layer.
    var ORGANS = ['Brain', 'Liver', 'Heart', 'Kidney', 'Muscle'];
    function drawNetwork(r) {
      var canvas = q('netCanvas');
      if (!canvas) return;
      var fit = fitCanvas(canvas, 0.82);
      var ctx = fit.ctx, w = fit.w, h = fit.h;
      ctx.clearRect(0, 0, w, h);

      var cbW = 12, cbGap = 26;
      var cx = (w - cbGap) / 2;
      var cy = h / 2 + 2;
      var radius = Math.min((w - cbGap) * 0.5, h * 0.5) * 0.62;
      var coh = coherenceUnit(r);
      var n = ORGANS.length;
      var nodes = [], i, j, a;
      for (i = 0; i < n; i++) {
        a = -Math.PI / 2 + (i / n) * 2 * Math.PI;
        nodes.push({ x: cx + Math.cos(a) * radius, y: cy + Math.sin(a) * radius, a: a });
      }

      // fully-connected edges
      ctx.strokeStyle = 'rgba(167, 243, 208, 0.18)';
      ctx.lineWidth = 1;
      for (i = 0; i < n; i++) {
        for (j = i + 1; j < n; j++) {
          ctx.beginPath(); ctx.moveTo(nodes[i].x, nodes[i].y); ctx.lineTo(nodes[j].x, nodes[j].y); ctx.stroke();
        }
      }

      // nodes (all share coherence → same color)
      var nodeR = Math.max(13, Math.min(20, radius * 0.34));
      ctx.font = "600 9px 'Cinzel', serif";
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      for (i = 0; i < n; i++) {
        var glow = ctx.createRadialGradient(nodes[i].x, nodes[i].y, 1, nodes[i].x, nodes[i].y, nodeR);
        glow.addColorStop(0, coherenceColor(coh, 0.95));
        glow.addColorStop(1, coherenceColor(coh, 0.65));
        ctx.fillStyle = glow;
        ctx.beginPath(); ctx.arc(nodes[i].x, nodes[i].y, nodeR, 0, 2 * Math.PI); ctx.fill();
        // label outside the ring
        ctx.fillStyle = 'rgba(226, 248, 237, 0.82)';
        var lr = nodeR + 11;
        ctx.fillText(ORGANS[i], nodes[i].x + Math.cos(nodes[i].a) * lr, nodes[i].y + Math.sin(nodes[i].a) * lr);
      }

      // colorbar (right edge): red(0) → yellow → green(1)
      var bx = w - cbW - 2, byTop = padTop(h), bH = h - 2 * byTop;
      var grad = ctx.createLinearGradient(0, byTop + bH, 0, byTop);
      grad.addColorStop(0, coherenceColor(0, 1));
      grad.addColorStop(0.5, coherenceColor(0.5, 1));
      grad.addColorStop(1, coherenceColor(1, 1));
      ctx.fillStyle = grad;
      ctx.fillRect(bx, byTop, cbW, bH);
      // current-coherence tick
      ctx.fillStyle = 'rgba(236, 253, 245, 0.95)';
      var ty = byTop + (1 - coh) * bH;
      ctx.beginPath(); ctx.moveTo(bx - 3, ty); ctx.lineTo(bx, ty - 3); ctx.lineTo(bx, ty + 3); ctx.closePath(); ctx.fill();
      ctx.fillStyle = 'rgba(220, 252, 231, 0.55)';
      ctx.font = "500 8px 'Cinzel', serif";
      ctx.textAlign = 'right';
      ctx.textBaseline = 'middle';
      ctx.fillText('1', bx - 4, byTop);
      ctx.fillText('0', bx - 4, byTop + bH);
    }
    function padTop(h) { return Math.max(8, h * 0.08); }

    var anim = { r: null, traceT0: 0, pending: false, running: false, rafId: 0 };
    var TRACE_MS = 700;
    var prefersReduced = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;

    function spiralLoop(ts) {
      if (!anim.r) { anim.running = false; return; }
      if (anim.pending) { anim.traceT0 = ts; anim.pending = false; }
      var elapsed = ts - anim.traceT0;
      var prog = TRACE_MS > 0 ? Math.min(1, elapsed / TRACE_MS) : 1;
      prog = 1 - Math.pow(1 - prog, 3); // easeOutCubic
      drawSpiral(anim.r, prog, ts / 1000);
      anim.rafId = window.requestAnimationFrame(spiralLoop);
    }

    function drawViz(r) {
      lastR = r;
      anim.r = r;
      drawRadar(r);
      drawTraj();
      drawNetwork(r);
      if (prefersReduced) {
        drawSpiral(r, 1, 0);
        return;
      }
      anim.pending = true; // restart trace from 0 on each change
      if (!anim.running) {
        anim.running = true;
        anim.rafId = window.requestAnimationFrame(spiralLoop);
      }
    }

    function syncAdvInputs(r, skipKey) {
      ADV_FIELDS.forEach(function (f) {
        if (f.key === skipKey) return;
        var input = q('adv-' + f.key);
        if (input) input.value = f.fmt(r);
      });
    }

    // ── Feature 1: audible Quantum Heartbeat (Web Audio) ────────────────
    // Tempo and timbre are a faithful mapping of real model outputs: coherent
    // → slow, clear "lub-dub"; degraded → faster, duller, irregular; collapsed
    // → a faint flatline tick. No invented data — just sonified coherence.
    var audio = { ctx: null, on: false, timeout: 0 };
    function audioToggle() {
      if (audio.on) { audioStop(); return; }
      var AC = window.AudioContext || window.webkitAudioContext;
      if (!AC) return;
      if (!audio.ctx) audio.ctx = new AC();
      if (audio.ctx.state === 'suspended') audio.ctx.resume();
      audio.on = true;
      var btn = q('heartBtn');
      if (btn) { btn.classList.add('active'); btn.setAttribute('aria-pressed', 'true'); }
      setText('heartLab', 'Beating');
      scheduleBeat();
    }
    function audioStop() {
      audio.on = false;
      if (audio.timeout) { clearTimeout(audio.timeout); audio.timeout = 0; }
      var btn = q('heartBtn');
      if (btn) { btn.classList.remove('active'); btn.setAttribute('aria-pressed', 'false'); }
      setText('heartLab', 'Heartbeat');
    }
    function scheduleBeat() {
      if (!audio.on || !audio.ctx || !lastR) return;
      playThump(lastR);
      var coh = coherenceUnit(lastR);
      var base = 1100 - (1 - coh) * 720;
      var jitter = (1 - coh) * base * 0.5 * (Math.random() * 2 - 1);
      audio.timeout = setTimeout(scheduleBeat, Math.max(260, base + jitter));
    }
    function playThump(r) {
      var ctx = audio.ctx; if (!ctx) return;
      var coh = coherenceUnit(r);
      var now = ctx.currentTime;
      var collapsed = !(r.tauCohS > 0);
      function pulse(t, freq, peak, dur) {
        var osc = ctx.createOscillator(), g = ctx.createGain();
        osc.type = 'sine';
        osc.frequency.setValueAtTime(freq, t);
        osc.frequency.exponentialRampToValueAtTime(Math.max(30, freq * 0.6), t + dur);
        g.gain.setValueAtTime(0.0001, t);
        g.gain.exponentialRampToValueAtTime(peak, t + 0.008);
        g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
        osc.connect(g); g.connect(ctx.destination);
        osc.start(t); osc.stop(t + dur + 0.02);
      }
      if (collapsed) { pulse(now, 38, 0.04, 0.28); return; }
      var baseFreq = 55 + coh * 50;
      var peak = 0.11 + coh * 0.12;
      var dur = 0.10 + coh * 0.15;
      pulse(now, baseFreq, peak, dur);
      pulse(now + 0.14, baseFreq * 0.78, peak * 0.7, dur * 0.9);
    }

    // ── Feature 5: live derivation chain (substituted numbers) ──────────
    function updateDerivation(r) {
      setText('dvE', 'E = e·Δψ = ' + r.energyJ.toExponential(2) + ' J');
      setText('dvNu', 'ω = E/ℏ → ν = ' + r.nuThz.toFixed(2) + ' THz');
      setText('dvLam', 'λ = c/ν = ' + r.wavelengthUm.toFixed(2) + ' μm');
      setText('dvDT', 'ΔT = W/λ − T_bath = ' + r.deltaTK.toFixed(1) + ' K');
      setText('dvM', 'm = k_B·T·ln2/c² = ' + r.infotonMass.toExponential(2) + ' kg');
      setText('dvTau', 'τ = ℏ/(k_B·ΔT) = ' + fmtTau(r.tauCohPs));
    }

    // ── Feature 6: JC-1 assay field sync ────────────────────────────────
    function updateAssay(r) {
      var jc1 = q('jc1');
      if (jc1 && document.activeElement !== jc1) jc1.value = jc1RatioFromPsi(r.psiMmV).toFixed(2);
      setText('jc1Psi', String(Math.round(r.psiMmV)));
    }

    // ── Feature 2: live conformance / reproducibility check ─────────────
    function relErr(a, b) {
      return Math.abs(a - b) / Math.max(Math.abs(b), 1e-300);
    }
    function runParity() {
      var rowsEl = q('reproRows'); if (!rowsEl) return;
      var fields = [['nu_thz', 'nuThz'], ['wavelength_um', 'wavelengthUm'], ['delta_t_k', 'deltaTK'], ['infoton_mass_kg', 'infotonMass']];
      var maxErr = 0, pass = 0, html = '';
      REFERENCE_VECTORS.forEach(function (vec) {
        var r = core.calculate(vec.psi);
        var rowMax = 0;
        fields.forEach(function (f) {
          var e = relErr(r[f[1]], vec[f[0]]);
          if (e > rowMax) rowMax = e;
        });
        if (rowMax > maxErr) maxErr = rowMax;
        var ok = rowMax <= VECTOR_TOL_REL;
        if (ok) pass++;
        html += '<div class="wgt-mito-repro-row ' + (ok ? 'ok' : 'fail') + '" data-psi="' + vec.psi + '">' +
          '<span class="wgt-mito-repro-psi">' + vec.psi + ' mV</span>' +
          '<span class="wgt-mito-repro-mark">' + (ok ? '✓' : '✕') + '</span>' +
          '<span class="wgt-mito-repro-err">' + (rowMax === 0 ? 'bit-exact' : '≤ ' + rowMax.toExponential(0)) + '</span>' +
          '</div>';
      });
      rowsEl.innerHTML = html;
      var allOk = pass === REFERENCE_VECTORS.length;
      var sumEl = q('reproSummary');
      if (sumEl) {
        sumEl.textContent = pass + ' / ' + REFERENCE_VECTORS.length + ' vectors reproduced · max rel error ' +
          (maxErr === 0 ? '0 (bit-exact)' : maxErr.toExponential(1)) + (allOk ? ' ✓' : '');
        sumEl.className = 'wgt-mito-repro-summary ' + (allOk ? 'ok' : 'fail');
      }
      highlightParity(currentPsi());
    }
    function highlightParity(psi) {
      var rows = root.querySelectorAll('.wgt-mito-repro-row');
      var p = Math.round(psi);
      for (var i = 0; i < rows.length; i++) {
        rows[i].classList.toggle('current', parseFloat(rows[i].getAttribute('data-psi')) === p);
      }
    }

    // ── Feature 3: shareable permalink + snapshot PNG ───────────────────
    function currentPsi() { var s = q('slider'); return s ? parseFloat(s.value) : 150; }
    function readPsiParam() {
      try {
        var m = /[?&]psi=([0-9.]+)/.exec(location.search);
        if (m) { var v = parseFloat(m[1]); if (isFinite(v)) return v; }
      } catch (e) {}
      return null;
    }
    function shareLink() {
      var psi = Math.round(currentPsi());
      var url = location.origin + location.pathname + '?psi=' + psi + location.hash;
      try { history.replaceState(null, '', url); } catch (e) {}
      var btn = q('shareBtn');
      function done(label) {
        if (!btn) return;
        btn.textContent = label;
        setTimeout(function () { btn.textContent = 'Share'; }, 1500);
      }
      if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(url).then(function () { done('Link copied'); }).catch(function () { done('Link in URL'); });
      } else { done('Link in URL'); }
    }
    function downloadSnapshot() {
      var r = lastR || core.calculate(currentPsi());
      var rgb = stateRgb(r.state.id);
      var scale = 2, W = 640, Hh = 384;
      var cv = document.createElement('canvas');
      cv.width = W * scale; cv.height = Hh * scale;
      var ctx = cv.getContext('2d');
      ctx.scale(scale, scale);
      ctx.fillStyle = '#0b2a1c'; ctx.fillRect(0, 0, W, Hh);
      ctx.fillStyle = 'rgba(110,231,183,0.10)'; ctx.fillRect(0, 0, W, 6);
      ctx.textBaseline = 'alphabetic';
      ctx.fillStyle = 'rgba(167,243,208,0.75)';
      ctx.font = "600 13px 'Inter', system-ui, sans-serif";
      ctx.fillText('VIRTUAL MITOCHONDRIA · QUANTUM HEARTBEAT', 34, 46);
      ctx.fillStyle = '#ecfdf5';
      ctx.font = "700 64px 'Inter', system-ui, sans-serif";
      ctx.fillText(Math.round(r.psiMmV) + ' mV', 34, 116);
      ctx.fillStyle = 'rgba(220,252,231,0.6)';
      ctx.font = "400 15px 'Inter', system-ui, sans-serif";
      ctx.fillText('membrane potential Δψm (input)', 34, 140);
      // state pill
      ctx.fillStyle = 'rgb(' + rgb[0] + ',' + rgb[1] + ',' + rgb[2] + ')';
      ctx.font = "700 18px 'Inter', system-ui, sans-serif";
      ctx.textAlign = 'right';
      ctx.fillText(r.state.display, W - 34, 110);
      ctx.textAlign = 'left';
      // metric grid
      var coh = coherenceUnit(r);
      var rows = [
        ['ν (heartbeat)', r.nuThz.toFixed(2) + ' THz'],
        ['λ', r.wavelengthUm.toFixed(2) + ' μm'],
        ['ΔT (coherence gap)', (r.deltaTK > 0 ? r.deltaTK.toFixed(1) : '—') + ' K'],
        ['Infoton mass', r.infotonMass.toExponential(2) + ' kg'],
        ['Coherence', (coh * 100).toFixed(0) + ' %'],
        ['τ', fmtTau(r.tauCohPs)],
      ];
      var gx = 34, gy = 188, cw = (W - 68) / 2, rh = 46;
      rows.forEach(function (row, i) {
        var x = gx + (i % 2) * cw, y = gy + Math.floor(i / 2) * rh;
        ctx.fillStyle = 'rgba(220,252,231,0.5)';
        ctx.font = "400 12px 'Inter', system-ui, sans-serif";
        ctx.fillText(row[0], x, y);
        ctx.fillStyle = '#d1fae5';
        ctx.font = "600 22px 'Inter', system-ui, sans-serif";
        ctx.fillText(row[1], x, y + 24);
      });
      ctx.fillStyle = 'rgba(167,243,208,0.55)';
      ctx.font = "400 12px 'Inter', system-ui, sans-serif";
      ctx.fillText('Research-use · deterministic · matches published Zenodo 18373065 reference (≤ 1e-9)', 34, Hh - 22);
      var a = document.createElement('a');
      a.href = cv.toDataURL('image/png');
      a.download = 'virtual-mitochondria-' + Math.round(r.psiMmV) + 'mV.png';
      document.body.appendChild(a); a.click(); document.body.removeChild(a);
    }

    // ── Feature 4: guided "cancer paradox" reveal ───────────────────────
    var tour = { i: -1, active: false };
    function tourShow(i) {
      if (i < 0 || i >= TOUR_STEPS.length) { tourEnd(); return; }
      tour.i = i; tour.active = true;
      var el = q('tour'); if (el) el.hidden = false;
      var s = TOUR_STEPS[i];
      setText('tourStep', 'Guided tour · ' + (i + 1) + ' / ' + TOUR_STEPS.length);
      setText('tourTitle', s.title);
      setText('tourText', s.body);
      var nextBtn = q('tourNext');
      if (nextBtn) nextBtn.textContent = (i === TOUR_STEPS.length - 1) ? 'Done' : 'Next →';
      animatePsiTo(s.psi, 1400);
    }
    function tourEnd() {
      tour.active = false;
      var el = q('tour'); if (el) el.hidden = true;
    }

    function apply(r) {
      setText('psiVal', String(Math.round(r.psiMmV)));
      setText('energy', r.energyJ.toExponential(3));
      setText('omega', r.omegaRadS.toExponential(3));
      setText('nu', r.nuThz.toFixed(2));
      setText('lambda', r.wavelengthUm.toFixed(2));
      setText('tWien', r.tWienK.toFixed(1));
      setText('deltaT', r.deltaTK.toFixed(1));
      setText('infoton', r.infotonMass.toExponential(3));
      setText('tau', fmtTau(r.tauCohPs));
      setText('atp', r.atp.toFixed(2));
      setText('ros', r.ros.toFixed(2));
      setText('vo2', r.vo2.toFixed(2));
      setText('gapReadout', (r.deltaTK > 0 ? r.deltaTK.toFixed(1) : '—') + ' K');
      setText('stateDesc', r.state.description);

      var badge = q('stateBadge');
      if (badge) {
        badge.textContent = r.state.display;
        badge.className = 'wgt-work-tag wgt-mito-state wgt-mito-state-big ' + r.state.cls;
      }

      var fill = q('cohFill');
      if (fill) fill.style.width = gapFillPct(r.deltaTK) + '%';

      var rgb = stateRgb(r.state.id);
      var leg = q('radarLeg');
      if (leg) leg.style.color = 'rgb(' + rgb[0] + ',' + rgb[1] + ',' + rgb[2] + ')';

      var cohNow = coherenceUnit(r);
      history.push({ coh: cohNow, risk: Math.max(0, Math.min(1, 1 - cohNow)) });
      if (history.length > HISTORY_MAX) history.shift();

      var contMarker = q('contMarker');
      if (contMarker) {
        contMarker.style.left = (cohNow * 100).toFixed(1) + '%';
        var zone = cohNow >= 0.9 ? 'Coherent' : cohNow >= 0.7 ? 'Drifting' : cohNow >= 0.5 ? 'Decoherent' : 'Collapsed';
        contMarker.title = zone + ' · coherence ' + (cohNow * 100).toFixed(0) + '%';
      }

      // diagnostic summary — qualitative bands over real quantities
      var entropy = Math.max(0, Math.min(1, r.deltaTK / ENTROPY_MAX));
      var cyclesNow = r.tauCohS > 0 ? (r.omegaRadS * r.tauCohS) / (2 * Math.PI) : 0;
      var curv = Math.max(0, Math.min(1, cyclesNow / CYCLES_HEALTHY));
      setDiag('phaseCoh', cohNow.toFixed(2), phaseLabel(cohNow), sevCoh(cohNow));
      setDiag('entropy', entropy.toFixed(2), entropyLabel(entropy), sevEntropy(entropy));
      setDiag('curv', curv.toFixed(2), curvLabel(curv), sevCurv(curv));
      setDiag('reso', r.nuThz.toFixed(1), resoLabel(cohNow), sevCoh(cohNow));

      var ffC = fissionFusionCoherence(r);
      var ffP = fissionFusionPsi(r);
      setText('ffCoh', ffC.toFixed(2) + '×  (' + (ffC >= 1 ? 'fission' : 'fusion') + ')');
      setText('ffPsi', ffP.toFixed(2) + '×  (' + (ffP >= 1 ? 'fission' : 'fusion') + ')');
      var ffNote = q('ffNote');
      if (ffNote) {
        var diverge = (ffC >= 1) !== (ffP >= 1);
        ffNote.textContent = diverge
          ? 'Models disagree here — coherence predicts ' + (ffC >= 1 ? 'fission' : 'fusion') +
            ', Δψ-literature predicts ' + (ffP >= 1 ? 'fission' : 'fusion') + '. Flag for January.'
          : 'Models agree: ' + (ffC >= 1 ? 'fission-dominant' : 'fusion-dominant') + '.';
      }

      updateDerivation(r);
      updateAssay(r);
      highlightParity(r.psiMmV);

      drawViz(r);

      PRESETS.forEach(function (p) {
        var btn = q('preset-' + p.psi);
        if (btn) btn.classList.toggle('active', Math.round(r.psiMmV) === p.psi);
      });

      if (!syncing) syncAdvInputs(r, null);
    }

    function setFromPsi(psiMmV, skipAdvKey) {
      if (!isFinite(psiMmV)) return;
      syncing = true;
      var r = core.calculate(psiMmV);
      apply(r);
      var slider = q('slider');
      if (slider) slider.value = String(clampPsi(psiMmV));
      syncAdvInputs(r, skipAdvKey);
      syncing = false;
    }

    var slider = q('slider');
    on(slider, 'input', function () {
      setFromPsi(parseFloat(slider.value), null);
    });

    PRESETS.forEach(function (p) {
      on(q('preset-' + p.psi), 'click', function () {
        setFromPsi(p.psi, null);
      });
    });

    // Simulate buttons — animate the single Δψ driver (grounded: just sweeps the input)
    var psiAnimRaf = 0;
    function animatePsiTo(target, dur) {
      if (psiAnimRaf) window.cancelAnimationFrame(psiAnimRaf);
      var sliderEl = q('slider');
      var start = sliderEl ? parseFloat(sliderEl.value) : 150;
      target = clampPsi(target);
      var t0 = null;
      function step(ts) {
        if (t0 === null) t0 = ts;
        var p = dur > 0 ? Math.min(1, (ts - t0) / dur) : 1;
        var e = 1 - Math.pow(1 - p, 3);
        setFromPsi(Math.round(start + (target - start) * e), null);
        if (p < 1) psiAnimRaf = window.requestAnimationFrame(step);
        else psiAnimRaf = 0;
      }
      psiAnimRaf = window.requestAnimationFrame(step);
    }
    on(q('simDisease'), 'click', function () { animatePsiTo(PSI_MAX, 2200); });
    on(q('simRecovery'), 'click', function () { animatePsiTo(150, 2200); });
    on(q('simUpdate'), 'click', function () { if (lastR) drawViz(lastR); });

    ADV_FIELDS.forEach(function (f) {
      var input = q('adv-' + f.key);
      if (!input) return;
      function handleAdv() {
        if (syncing) return;
        var val = parseFloat(input.value);
        if (!isFinite(val) || val <= 0) return;
        var fn = core[f.inverse];
        if (!fn) return;
        var psi = fn(val);
        if (!isFinite(psi)) return;
        setFromPsi(psi, f.key);
      }
      on(input, 'input', handleAdv);
      on(input, 'change', handleAdv);
    });

    on(q('copyBtn'), 'click', function () {
      var sliderEl = q('slider');
      var psi = sliderEl ? parseFloat(sliderEl.value) : 150;
      var text = JSON.stringify(core.snapshot(psi), null, 2);
      var btn = q('copyBtn');
      function done() {
        if (!btn) return;
        btn.textContent = 'Copied';
        setTimeout(function () { btn.textContent = 'Copy parameters'; }, 1600);
      }
      if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(text).then(done).catch(function () {
          window.prompt('Copy parameters JSON:', text);
          done();
        });
      } else {
        window.prompt('Copy parameters JSON:', text);
        done();
      }
    });

    on(q('heartBtn'), 'click', audioToggle);
    on(q('shareBtn'), 'click', shareLink);
    on(q('snapBtn'), 'click', downloadSnapshot);
    on(q('tourBtn'), 'click', function () { tourShow(0); });
    on(q('tourSkip'), 'click', tourEnd);
    on(q('tourNext'), 'click', function () {
      if (tour.i >= TOUR_STEPS.length - 1) tourEnd(); else tourShow(tour.i + 1);
    });
    on(q('reproBtn'), 'click', function () {
      var sumEl = q('reproSummary');
      if (sumEl) { sumEl.textContent = 'Re-running in-browser…'; sumEl.className = 'wgt-mito-repro-summary'; }
      setTimeout(runParity, 320);
    });
    on(q('jc1'), 'input', function () {
      if (syncing) return;
      var ratio = parseFloat(q('jc1').value);
      var psi = psiFromJc1Ratio(ratio);
      if (psi == null || !isFinite(psi)) return;
      setText('jc1Psi', String(Math.round(clampPsi(psi))));
      setFromPsi(psi, null);
    });

    var resizeRaf = 0;
    function onResize() {
      if (resizeRaf) return;
      resizeRaf = window.requestAnimationFrame(function () {
        resizeRaf = 0;
        if (!lastR) return;
        drawRadar(lastR);
        drawTraj();
        drawNetwork(lastR);
        if (prefersReduced) drawSpiral(lastR, 1, 0);
        // the spiral animation loop self-corrects canvas size each frame
      });
    }
    on(window, 'resize', onResize);

    var initPsi = readPsiParam();
    setFromPsi(initPsi != null ? initPsi : 150, null);
    runParity();

    function snapshot() {
      var sliderEl = q('slider');
      var psi = sliderEl ? parseFloat(sliderEl.value) : 150;
      return core.calculate(psi);
    }

    return {
      destroy: function () {
        audioStop();
        if (audio.ctx && audio.ctx.close) { try { audio.ctx.close(); } catch (e) {} }
        if (resizeRaf) window.cancelAnimationFrame(resizeRaf);
        if (anim.rafId) window.cancelAnimationFrame(anim.rafId);
        if (psiAnimRaf) window.cancelAnimationFrame(psiAnimRaf);
        anim.running = false;
        anim.r = null;
        listeners.forEach(function (pair) {
          pair[0].removeEventListener(pair[1], pair[2]);
        });
        root.innerHTML = '';
      },
      snapshot: snapshot,
    };
  }

  global.P30Widgets = global.P30Widgets || {};
  global.P30Widgets.mitochondria = { mount: mountMitochondria };
})(window);
