#!/usr/bin/env python3
"""Generate fpga/monitor_rom/corpus_data.c from spec/canonical_corpus.txt."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TIER1 = json.loads((ROOT / "spec" / "tier1_alphabet.json").read_text(encoding="utf-8"))
CHAR_TO_VAL = {e[0]: e[1] for e in TIER1["tier1"]}
TOT = [1, 7, 11, 13, 17, 19, 23, 29]


def position_value(ch: str, index: int) -> int:
    if ch in CHAR_TO_VAL:
        return CHAR_TO_VAL[ch]
    return index * 30 + TOT[ord(ch) % 8]


def main() -> None:
    text = (ROOT / "spec" / "canonical_corpus.txt").read_text(encoding="utf-8").strip("\n\r")
    if len(text) != 163:
        raise SystemExit(f"corpus len {len(text)} != 163")
    positions = [position_value(ch, i) for i, ch in enumerate(text)]
    out = ROOT / "fpga" / "monitor_rom" / "corpus_data.c"
    lines = [
        "/* Auto-generated by tools/gen_corpus_firmware.py */",
        '#include "p30_soak.h"',
        "",
        f"const unsigned char corpus_utf8[CORPUS_LEN] = {{",
    ]
    for i in range(0, len(text), 16):
        chunk = text[i : i + 16]
        hexes = ", ".join(f"0x{b:02x}" for b in chunk.encode("utf-8"))
        lines.append(f"    {hexes},")
    lines.append("};")
    lines.append("")
    lines.append("const unsigned int corpus_pos[CORPUS_LEN] = {")
    for i in range(0, len(positions), 8):
        chunk = positions[i : i + 8]
        lines.append("    " + ", ".join(str(p) for p in chunk) + ",")
    lines.append("};")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
