#!/usr/bin/env python3
"""Generate fpga/monitor_rom/corpus_data.c from spec/canonical_corpus.txt."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TIER1 = json.loads((ROOT / "spec" / "tier1_alphabet.json").read_text(encoding="utf-8"))
CHAR_TO_VAL = {e[0]: e[1] for e in TIER1["tier1"]}
TOT = [1, 7, 11, 13, 17, 19, 23, 29]


def position_value(ch: str, index: int) -> int:
    if ch in CHAR_TO_VAL:
        return CHAR_TO_VAL[ch]
    # Escape: first UTF-8 byte (matches Rust locate_totative_byte).
    return index * 30 + TOT[ch.encode("utf-8")[0] % 8]


def render() -> str:
    text = (ROOT / "spec" / "canonical_corpus.txt").read_text(encoding="utf-8").strip("\n\r")
    if len(text) != 163:
        raise SystemExit(f"corpus len {len(text)} != 163")
    positions = [position_value(ch, i) for i, ch in enumerate(text)]
    lines = [
        "/* Auto-generated by tools/gen_corpus_firmware.py */",
        '#include "p30_soak.h"',
        "",
        f"const unsigned char corpus_utf8[CORPUS_LEN] = {{",
    ]
    for i in range(0, len(text), 16):
        chunk = text[i : i + 16]
        hexes = ", ".join(f"0x{b:02x}" for b in chunk.encode("utf-8"))
        lines.append(f"    {hexes},")
    lines.append("};")
    lines.append("")
    lines.append("const unsigned int corpus_pos[CORPUS_LEN] = {")
    for i in range(0, len(positions), 8):
        chunk = positions[i : i + 8]
        lines.append("    " + ", ".join(str(p) for p in chunk) + ",")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    p = argparse.ArgumentParser(description="Generate fpga/monitor_rom/corpus_data.c")
    p.add_argument(
        "--check",
        action="store_true",
        help="Fail if the committed corpus_data.c is out of date (do not write)",
    )
    args = p.parse_args()
    out = ROOT / "fpga" / "monitor_rom" / "corpus_data.c"
    content = render()
    if args.check:
        current = out.read_text(encoding="utf-8") if out.exists() else None
        if current != content:
            raise SystemExit(f"{out} is stale — run: python tools/gen_corpus_firmware.py")
        print(f"{out} up to date")
        return
    out.write_text(content, encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
