#!/usr/bin/env python3
"""Golden-test fpga/p30_pack.v against emulator/p30emu/src/unit.rs semantics."""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from math import gcd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FPGA = ROOT / "fpga"
UNIT_MASK = 0x3FFF_FFFF
TOTATIVES = [1, 7, 11, 13, 17, 19, 23, 29]


def pack_quad(units: list[int]) -> bytes:
    bits = [0] * 120
    for ui, unit in enumerate(units):
        u = unit & UNIT_MASK
        for b in range(30):
            if (u >> b) & 1:
                bits[ui * 30 + b] = 1
    out = bytearray(15)
    for byte_idx in range(15):
        v = 0
        for bit in range(8):
            if bits[byte_idx * 8 + bit]:
                v |= 1 << bit
        out[byte_idx] = v
    return bytes(out)


def unpack_quad(data: bytes) -> list[int]:
    assert len(data) == 15
    bits = [0] * 120
    for byte_idx, byte in enumerate(data):
        for bit in range(8):
            if (byte >> bit) & 1:
                bits[byte_idx * 8 + bit] = 1
    units = []
    for ui in range(4):
        u = 0
        for b in range(30):
            if bits[ui * 30 + b]:
                u |= 1 << b
        units.append(u)
    return units


def lane_hex(data: bytes) -> str:
    n = int.from_bytes(data, "little")
    return f"120'h{n:030x}"


def valid_unit(value: int) -> bool:
    v = value & UNIT_MASK
    return v != 0 and gcd(v, 30) == 1


def golden_vectors() -> list[dict]:
    vectors = []
    vectors.append(
        {
            "id": "totatives",
            "units": TOTATIVES[:4],
        }
    )
    vectors.append(
        {
            "id": "totatives_alt",
            "units": TOTATIVES[2:6],
        }
    )
    for bit in (0, 1, 29):
        vectors.append({"id": f"bit_{bit}", "units": [1 << bit, 7, 11, 13]})
    vectors.append(
        {
            "id": "large_coprime",
            "units": [0x3FFF_FFF1, 0x3FFF_FFF7, 0x3FFF_FFFD, 0x3FFF_FFE3],
        }
    )
    tier1 = json.loads((ROOT / "spec" / "tier1_alphabet.json").read_text(encoding="utf-8"))
    char_to_val = {e[0]: e[1] for e in tier1["tier1"]}
    vectors.append(
        {"id": "corpus_prefix", "units": [char_to_val[c] for c in "The "]}
    )
    for v in vectors:
        raw = pack_quad(v["units"])
        v["bytes_hex"] = raw.hex()
        assert unpack_quad(raw) == v["units"]
    return vectors


def write_verilog_include(vectors: list[dict], path: Path) -> None:
    lines = ["// Auto-generated by tools/verify_p30_pack.py — do not edit"]
    for v in vectors:
        u = v["units"]
        lane = lane_hex(bytes.fromhex(v["bytes_hex"]))
        lines.append(f"// {v['id']}")
        lines.append(
            f"unit0 = 30'd{u[0]}; unit1 = 30'd{u[1]}; "
            f"unit2 = 30'd{u[2]}; unit3 = 30'd{u[3]};"
        )
        lines.append("#1;")
        lines.append(
            f"if (bytes_out !== {lane}) $fatal(1, \"pack fail: {v['id']}\");"
        )
        lines.append(
            f"if (unit0_r !== 30'd{u[0]} || unit1_r !== 30'd{u[1]} || "
            f"unit2_r !== 30'd{u[2]} || unit3_r !== 30'd{u[3]}) "
            f"$fatal(1, \"unpack fail: {v['id']}\");"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run_python_golden(vectors: list[dict]) -> None:
    for v in vectors:
        raw = bytes.fromhex(v["bytes_hex"])
        back = unpack_quad(raw)
        assert back == v["units"], v["id"]
        assert pack_quad(back) == raw, v["id"]
    print(f"python golden: {len(vectors)} vectors OK")


def run_iverilog() -> bool:
    iverilog = shutil.which("iverilog")
    vvp = shutil.which("vvp")
    if not iverilog or not vvp:
        print("iverilog: skipped (not installed)")
        return False
    out = FPGA / "tb_p30_pack.out"
    subprocess.run(
        [iverilog, "-o", str(out), "p30_pack.v", "tb_p30_pack.v"],
        cwd=FPGA,
        check=True,
    )
    result = subprocess.run([vvp, str(out)], cwd=FPGA, capture_output=True, text=True)
    print(result.stdout, end="")
    if result.returncode != 0 or "PASS" not in result.stdout:
        if result.stderr:
            print(result.stderr, file=sys.stderr)
        raise SystemExit("iverilog simulation failed")
    print("iverilog golden: PASS")
    return True


def main() -> None:
    vectors = golden_vectors()
    spec_path = ROOT / "spec" / "pack_vectors.json"
    spec_path.write_text(
        json.dumps({"vector_count": len(vectors), "vectors": vectors}, indent=2) + "\n",
        encoding="utf-8",
    )
    write_verilog_include(vectors, FPGA / "golden_pack.inc")
    run_python_golden(vectors)
    run_iverilog()
    print("verify_p30_pack: PASS")


if __name__ == "__main__":
    main()
